aws_credentials: ENCRYPTED[76d529d4c79c4c3ff212d38ce920e0be50501ed4c657128c487cf7d9742fb57395029871ccf697bbe07c0a481bbbab6b]

task:
  ec2_instance:
    image: ami-03790f6959fc34ef3
    type: t2.micro
    region: us-east-1
  script:
    - apt-get update && apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip ffmpeg aria2
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: nw2.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/164771721' --header 'Upgrade-Insecure-Requests: 1' 'https://nw2.seedr.cc/ff_get/876366295/The.Last.Naruto.The.Movie.2014.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4?st=GfNTsnwY2wrN2laDsj4Mdg&e=1616675221' --out 'The.Last.Naruto.The.Movie.2014.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4'"
  binaries_artifacts:
    path: "The.Last.Naruto.The.Movie.2014.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4"
